<?php
/******************************************
Русский язык
Admin Category Language
******************************************/

$lang['categories']					= 'Категории';
$lang['error_must_select']			= 'Вы должны выбрать Категории для перестановки';
$lang['error_not_found']			= 'Запрошенная Категория не найдена.';
$lang['organize_category']			= 'Переставлена Категория "%s"';
$lang['organize']					= 'Переставить';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Рекдактор Категории';
$lang['name']						= 'Название';
$lang['slug']						= 'URL адрес';
$lang['description']				= 'Описание';
$lang['excerpt']					= 'Отрывок';
$lang['sequence']					= 'Последовательность';
$lang['image']						= 'Рисунок';
$lang['seo_title']					= 'SEO Заголовок';
$lang['meta']						= 'Мета Данные';
$lang['message_category_saved']		= 'Категория сохранена!';
$lang['error_file_upload']			= '<p>Вы не выбравли файл для загрузки.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'Категория удалена.';
$lang['current_file']				= 'Текущий файл';
$lang['confirm_delete_category']	= 'Удалить Категорию?';
$lang['add_new_category']			= 'Добавить';
$lang['no_categories']				= 'Сейчас нет категория';
$lang['attributes']					= 'Атрибуты';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Родитель';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Перетащите товары в нужном порядке.';
$lang['sku']						= 'Артикул';
$lang['price']						= 'Цена';
$lang['sale']						= 'Распродажа';
$lang['max_file_size']				= 'Макс. размер файла';